swagger: "2.0"
schemes:
  - http
basePath: /
info:
  version: 1.0.0
  title: Python Microservice API
  description: "username: profAvery \n password: password"
tags:
  - name: default
    description: default tag

paths:
  /home/{username}:
    get:
      summary: get timeline from the user's friends
      parameters:
        - in: path
          name: username
          schema:
            type: string
          description: try ProfAvery
      produces:
        - application/text
      responses:
        "200":
          description: OK
      tags:
        - timeline

  /posts/?username={username}:
    get:
      summary: get timeline from the user
      parameters:
        - in: path
          name: username
          schema:
            type: string
          description: try ProfAvery
      produces:
        - application/text
      responses:
        "200":
          description: OK
      tags:
        - timeline

  /posts/:
    get:
      summary: get timeline from all users
      produces:
        - application/text
      responses:
        "200":
          description: OK
      tags:
        - timeline
